# Default deny all traffic
# This ensures that only explicitly allowed traffic is permitted
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-deny-all
  namespace: default
spec:
  endpointSelector:
    matchLabels: {}
  egress:
    - toCIDR:
      - 0.0.0.0/0
      toPorts:
        - ports:
          - port: "53"
            protocol: UDP
  ingress:
    - fromEntities:
      - kube-apiserver
